apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cepg-aa-std-pvc
  namespace: "82265640"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cepg-aa-std-rwmany
  resources:
    requests:
      storage: 1Gi
